#ifndef GOBLIB_DATETIME_VERSION_HPP
#define GOBLIB_DATETIME_VERSION_HPP

#define GOBLIB_DATETIME_VERSION_MAJOR 0
#define GOBLIB_DATETIME_VERSION_MINOR 1
#define GOBLIB_DATETIME_VERSION_PATCH 0

#define GOBLIB_DATETIME_VERSION_STRINGIFY_AGAIN(x) #x
#define GOBLIB_DATETIME_VERSION_STRINGIFY(x) GOBLIB_DATETIME_VERSION_STRINGIFY_AGAIN(x)

#define GOBLIB_DATETIME_VERSION_VALUE ((GOBLIB_DATETIME_VERSION_MAJOR << 16) | (GOBLIB_DATETIME_VERSION_MINOR << 8) | (GOBLIB_DATETIME_VERSION_PATCH))
#define GOBLIB_DATETIME_VERSION_STRING GOBLIB_DATETIME_VERSION_STRINGIFY(GOBLIB_DATETIME_VERSION_MAJOR.GOBLIB_DATETIME_VERSION_MINOR.GOBLIB_DATETIME_VERSION_PATCH)

#endif
